name: Cortex Security Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  cortex-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Open-Source Checkov Scan
        uses: bridgecrewio/checkov-action@master
        with:
          directory: '.'
          framework: 'terraform'
          soft_fail: true
